# Generated by Django 3.0.6 on 2020-05-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('it', 'IT'), ('groceries', 'Groceries'), ('cosmetics', 'Cosmetics')], max_length=20),
        ),
    ]
