# Generated by Django 3.0.6 on 2020-05-18 06:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0002_auto_20200515_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='color',
            field=models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('black', 'Black')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
